# Generated by Django 5.1.6 on 2025-02-13 07:24

import django.db.models.deletion
import newapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=newapp.models.getfileName)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.BooleanField(default=False, help_text='0-Show,1-Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Vender', models.CharField(max_length=100)),
                ('Product_image', models.ImageField(blank=True, null=True, upload_to=newapp.models.getfileName)),
                ('Quantity', models.IntegerField()),
                ('Own_price', models.FloatField()),
                ('Selling_price', models.FloatField()),
                ('description', models.TextField(max_length=1000)),
                ('status', models.BooleanField(default=False, help_text='0-Show,1-Hidden')),
                ('Trending', models.BooleanField(default=False, help_text='0-default,1-Trending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.catagory')),
            ],
        ),
    ]
